# Generated by Django 6.0.3 on 2026-09-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_facultad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
