# Generated by Django 6.0.3 on 2026-06-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tipo', models.CharField(choices=[('PAR', 'Parcial'), ('FIN', 'Final'), ('PRO', 'Promoción')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sede', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('año_dictado', models.IntegerField()),
                ('creditos_totales', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('CUR', 'Cursando'), ('REG', 'Regular'), ('APR', 'Aprobada'), ('REC', 'Recursando')], default='PEN', max_length=3)),
                ('es_promocionable', models.BooleanField(default=True)),
            ],
        ),
    ]
