# Generated by Django 6.0.3 on 2026-05-12 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sede', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='plan_estudio_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facultad'),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('año_dictado', models.IntegerField()),
                ('creditos_totales', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('CUR', 'Cursando'), ('REG', 'Regular'), ('APR', 'Aprobada'), ('REC', 'Recursando')], default='PEN', max_length=3)),
                ('es_promocionable', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tipo', models.CharField(choices=[('PAR', 'Parcial'), ('FIN', 'Final'), ('PRO', 'Promoción')], max_length=3)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='core.materia')),
            ],
        ),
    ]
