# Generated by Django 6.0.3 on 2026-09-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['-fecha'], 'verbose_name': 'Examen', 'verbose_name_plural': 'Exámenes'},
        ),
        migrations.AlterModelOptions(
            name='facultad',
            options={'ordering': ['nombre'], 'verbose_name': 'Facultad', 'verbose_name_plural': 'Facultades'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['año_dictado', 'nombre'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
    ]
